# TEST PLAN
## Table no: High level test plan

| **Test ID** | **Description**                                              | **Exp I/P** | **Exp O/P** | **Actual Out** |**Type Of Test**  |    
|-------------|--------------------------------------------------------------|-------------|-------------|----------------|------------------|
|  H_01       | Testing the values of the Resistor color codes for the two given bands|Color bands depending on the type|resistance value  | Session cannot be tested as it contains input parameters inside functions | Requirement based  |
|  H_02       | Testing capacitive and inductive reactance value generation | capacitor/inductor vales and frequency values | Capacitive/inductive reactance  |Capacitive/inductive reactance PASS | Requirement based    |
|  H_03       | Testing battery data values based on voltage, current and power rating | voltage,current,resistance input and structure pointer function to reference the values | Battery power rating and type | same and testing status PASSED | Requirement based    |
|  H_04       | Testing series resistance based on the input parameters for resistive, capacitive, inductive and RLC circuits | checking parameter, function pointers based on the respective reactance values | Series overall reactance based on circuit type and current value | Not passed | Scenario based |
|  H_05       | Testing parallel resistance based on the input parameters for resistive, capacitive, inductive and RLC circuits | checking parameter, function pointers based on the respective reactance values | parallel overall reactance based on circuit type and current value | Not passed | Scenario based |
|  H_06       | Testing power and life expectancy of the battery based on the voltage, current, time and power rating inputs | voltage, current, time and power rating | power rating of the battery and batter life in days depending on the user choice | Same as expected, Action passed | Requirement based |

## Table no: Low level test plan

| **Test ID** | **Description**                                              | **Exp IN** | **Exp OUT** | **Actual Out**  |**Type Of Test**  |    
|-------------|--------------------------------------------------------------|------------|-------------|-----------------|------------------|
|  L_01       | Entering the values of the resistor color codes as a seperate function and calling the function to check the output|1. resistor band value: a) for 4 band, 3 values b) for 5 band, 4 values and store in an array |overall resistance value |  Session cannot be tested as it contains input parameters inside functions | Requirement based |
|  L_02       | Entering capacitor value, frequency value and passing them as function parameters in the form of arguments, using structure pointers in main| 1. capacitor value, 2. Capacitor units, 3. Frequency value, 4. Frequency units | Net capacitance|Status same as expected, PASSED | Scenario based    |
|  L_03       | Entering inductor value, frequency value and passing them as function parameters in the form of arguments, using structure pointers in main| 1. inductor value, 2. inductor units, 3. Frequency value, 4. Frequency units|Net inductance|Status same as expected, PASSED | Scenario based    |
|  L_04       | Checking the series resistance function for various known and unknown input values of resistances, known values of inductances and capacitance to calculate series overall resistance and current | 1.) Resistor input: a) known- resistor value and units b) unknown - color codes 2) capacitor and inductor value and unit input | Overall series resistance of the system and current requirement of the system | Test cases fail as argument does not take structure pointers | Scenario based |
|  L_05       | Checking the parallel resistance function for various known and unknown input values of resistances, known values of inductances and capacitance to calculate parallel overall resistance and current | 1.) Resistor input: a) known- resistor value and units b) unknown - color codes 2) capacitor and inductor value and unit input | Overall parallel resistance of the system and current requirement of the system | Test cases fail as argument does not take structure pointers | Scenario based |
|  L_06       | Calculating battery input values as battery data input using funmction pointers and sending variables as arguments | 1. checking variable 2. voltage variable 3. current variable 4. resistance value 5. units | Battery information based on voltage and power rating and print power rating | Same as expected, PASSED | Scenario based |
|  L_07       | Testing the series and parallel RLC function for various known and unknown input values of resistances, known values of inductances and capacitance to calculate series and parallel overall RLC resistance and current | 1.) Resistor input: a) known- resistor value and units b) unknown - color codes 2) capacitor and inductor value and unit input 3. frequency input 4. checker variable for series or parallel | Overall series and parallel RLC resistance of the system and current requirement of the system | Test cases fail as argument does not take structure pointers | Scenario based |
| L_08        | Testing power and life function by giving the respective structure pointers as arguments to find the power rating and circuit life as parameters | 1. Input pointer variables stored as structure to access dynamic memory 2. input voltage and resistance values | Overall power consumption and rating, lifetime in number of days | Session cannot be tested as it contains other input parameters in the function | Requirement based |
